version: "3.9"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  runserver:
    &runserver
      build: .
      command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py loaddata fixtures.json && python manage.py runserver 0.0.0.0:8000"
      volumes:
        - ./src/:/code/
      ports:
        - "8000:8000"
      depends_on:
        - db
        - celery

  autotests:
    <<: *runserver
    command: bash -c "python manage.py test"

  redis:
    image: redis:alpine

  celery:
    build: .
    command: celery -A core worker -l info
    volumes:
      - ./src/:/code/
    depends_on:
      - redis