# Generated by Django 3.2.5 on 2021-07-28 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('counter', models.IntegerField(default=0, verbose_name='Counter')),
                ('spec_attrs', models.JSONField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('name', models.CharField(max_length=30, verbose_name='Тип контента')),
                ('schema', models.JSONField(default=dict)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('contents', models.ManyToManyField(to='page.Content')),
            ],
            options={
                'verbose_name': 'page',
                'verbose_name_plural': 'page',
            },
        ),
        migrations.AddField(
            model_name='content',
            name='media_content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page.mediacontenttype'),
        ),
    ]
